version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 30
  target-branch: build/dependency-updates
  commit-message:
    prefix: "build"
    include: "scope"
