version: 2.1

commands:
  npm-auth:
    description: Authenticate with NPM registry
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

jobs:
  "Lint and Test":
    docker:
      - image: node:12.16.1-alpine3.9
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: apk update && apk upgrade && apk add --no-cache bash git
      - run:
          name: Check branch name
          command: >
            if [ "${CIRCLE_BRANCH}" != "master" ];
            then
              npm run check:branch-name
            fi
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}
      - run:
          name: Install npm modules
          command: npm ci
      - run:
          name: Run Eslint & Prettier
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Check squashed commit messages
          command: >
            if [ "${CIRCLE_BRANCH}" != "master" ];
            then
              npm run check:commits-squashed
            fi
      - run:
          name: Lint commit message in feature branch
          command: >
            if [ "${CIRCLE_BRANCH}" != "master" ];
            then
              npm run commitlint:feature-to-master-branch
            fi
  "Release Library":
    working_directory: ~/ttsa-npm-lib
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - npm-auth
      - run:
          name: Install library dependencies
          command: npm ci
      - run:
          name: Release
          command: npm run release
      - run:
          name: Save library release git hash
          command: echo $(git rev-parse HEAD) > ~/ttsa-npm-lib/release-sha.txt
      - persist_to_workspace:
          root: ~/ttsa-npm-lib
          paths:
            - ./release-sha.txt

workflows:
  version: 2
  "Lint and Test > Release Library":
    jobs:
      - "Lint and Test":
          filters:
            branches:
              only: master
      - "Release Library":
          context: testosa-release
          filters:
            branches:
              only: master
          requires:
            - "Lint and Test"
